version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    # environment:
    #    - .env # MongoDB URI for the FastAPI app
    env_file:
      - .env
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local